parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        default_connection:       default
        connections:
            default:
                dbname:               bd1
                host:                 localhost
                port:                 3306
                user:                 felipe
                password:             felipe.1320
                driver:               pdo_mysql

            customer:
                dbname:               bd2
                host:                 localhost
                port:                 3306
                user:                 felipe
                password:             felipe.1320
                driver:               pdo_mysql
#                  server_version:   5.7
        # With Symfony 3.3, remove the `resolve:` prefix
#        url: '%env(resolve:DATABASE_URL)%'
#    orm:
#        default_entity_manager:   default
#        entity_managers:
#              default:
#                  connection:       default
#                  mappings:
#                        App:
#                            is_bundle: false
#                            type: annotation
#                            dir: '%kernel.project_dir%/src/Entity'
#                            prefix: 'App\Entity'
#                            alias:
#              customer:
#                  connection:       customer
#                    mappings:
#                        App:
#                            is_bundle: false
#                            type: annotation
#                            dir: '%kernel.project_dir%/src/Entity'
#                            prefix: 'App\Entity'
#                            alias:

#        auto_generate_proxy_classes: '%kernel.debug%'
#        naming_strategy: doctrine.orm.naming_strategy.underscore
#        auto_mapping: true
#        mappings:
#            App:
#                is_bundle: false
#                type: annotation
#                dir: '%kernel.project_dir%/src/Entity'
#                prefix: 'App\Entity'
#                alias: App
